site_name: University of Nottingham
theme: 'material'
repo_url: 'https://github.com/UniversityOfNottingham/universityofnottingham.github.io'
edit_uri: 'edit/source/docs/'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  repo_icon: github

nav:
  - Home: index.md
  - Policies: policies.md
  - Standards:
    - Target Platforms: standards/target-platforms.md
    - Version Control: standards/version-control.md
    - Versioning: standards/versioning.md
    - Continuous Integration: standards/continuous-integration.md
    - Code Reviews: standards/code-reviews.md
    - JavaScript: standards/javascript.md
    - CSS: standards/css.md
    - PHP: standards/php.md
    - .NET:
      - Overview: standards/dotnet/index.md
      - C#: standards/dotnet/c-sharp.md
      - NuGet Packages: standards/dotnet/packages.md
      - .NET Core:
        - Approved Technologies: standards/dotnet/core/approved-technologies.md
      - .NET Framework:
        - Approved Technologies: standards/dotnet/fx/approved-technologies.md
  - Guidelines:
    - Recommended Tools: guidelines/recommended-tools.md
    - Packages: guidelines/packages.md
    - .NET:
      - Starting a new Project: guidelines/dotnet/new-project.md
      - .NET Framework Environment Setup: guidelines/dotnet/fx-environment-setup.md
    - SCRUM in Azure DevOps:
      - Overview: guidelines/azure-devops-scrum/index.md
      - Glossary: guidelines/azure-devops-scrum/glossary.md
      - SCRUM: guidelines/azure-devops-scrum/scrum.md
      - Definition of Done: guidelines/azure-devops-scrum/definition-of-done.md
      - Azure DevOps: guidelines/azure-devops-scrum/azure-devops.md
      - Azure DevOps Setup: guidelines/azure-devops-scrum/azure-devops-setup.md
      - WITS: guidelines/azure-devops-scrum/wits.md
      - Customisation: guidelines/azure-devops-scrum/customisation.md