site_name: University of Nottingham
theme: 'material'
repo_url: 'https://github.com/UniversityOfNottingham/universityofnottingham.github.io'
edit_uri: 'edit/source/docs/'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
extra:
  repo_icon: github

pages:
  - Home: index.md
  - Policies: policies.md
  - Standards:
    - Target Platforms: Standards/target-platforms.md
    - Version Control: Standards/version-control.md
    - Versioning: Standards/versioning.md
    - Continuous Integration: Standards/continuous-integration.md
    - Code Reviews: Standards/code-reviews.md
    - JavaScript: Standards/javascript.md
    - CSS: Standards/css.md
    - PHP: Standards/php.md
